(define (problem arm_ipar_pancake_problem-problem)
 (:domain arm_ipar_pancake_problem-domain)
 (:init
              (= (pancake_0) 2)
              (= (pancake_1) 3)
              (= (pancake_2) 0)
              (= (pancake_3) 4)
              (= (pancake_4) 1)
              (= (total-cost) 0)
 )
 (:goal (and 
           (= (pancake_0) 0)
           (= (pancake_1) 1)
           (= (pancake_2) 2)
           (= (pancake_3) 3)
           (= (pancake_4) 4)
        )
 )
 (:metric minimize (total-cost))
)
