;; Generated by generate_rainbowttles_NO_constants.py
;; seed=121702 profile=optimal-prefix capacity=4 colours=3 bottles=5 scramble_steps=6
;; Constant-free fixed instance: empty is an ordinary problem object.
(define (problem rainbowttles-12-constant-free)
 (:domain rainbowttles-constant-free)
 (:objects
    bottle01 bottle02 bottle03 bottle04 bottle05 - bottle
    red green blue empty - colour
 )
 (:init
  (real-colour red)
  (real-colour green)
  (real-colour blue)
  (empty-colour empty)

  (= (bottle-capacity bottle01) 4)
  (= (bottle-capacity bottle02) 4)
  (= (bottle-capacity bottle03) 4)
  (= (bottle-capacity bottle04) 4)
  (= (bottle-capacity bottle05) 4)

  (= (colour-segments bottle01 red) 2)
  (= (colour-segments bottle01 green) 1)
  (= (colour-segments bottle01 blue) 0)
  (= (colour-segments bottle01 empty) 0)
  (= (segments-filled bottle01) 3)
  (upper-colour bottle01 green)
  (colour-below bottle01 green red)
  (colour-below bottle01 red empty)

  (= (colour-segments bottle02 red) 0)
  (= (colour-segments bottle02 green) 1)
  (= (colour-segments bottle02 blue) 0)
  (= (colour-segments bottle02 empty) 0)
  (= (segments-filled bottle02) 1)
  (upper-colour bottle02 green)
  (colour-below bottle02 green empty)

  (= (colour-segments bottle03 red) 0)
  (= (colour-segments bottle03 green) 1)
  (= (colour-segments bottle03 blue) 2)
  (= (colour-segments bottle03 empty) 0)
  (= (segments-filled bottle03) 3)
  (upper-colour bottle03 green)
  (colour-below bottle03 green blue)
  (colour-below bottle03 blue empty)

  (= (colour-segments bottle04 red) 0)
  (= (colour-segments bottle04 green) 1)
  (= (colour-segments bottle04 blue) 1)
  (= (colour-segments bottle04 empty) 0)
  (= (segments-filled bottle04) 2)
  (upper-colour bottle04 blue)
  (colour-below bottle04 blue green)
  (colour-below bottle04 green empty)

  (= (colour-segments bottle05 red) 2)
  (= (colour-segments bottle05 green) 0)
  (= (colour-segments bottle05 blue) 1)
  (= (colour-segments bottle05 empty) 0)
  (= (segments-filled bottle05) 3)
  (upper-colour bottle05 blue)
  (colour-below bottle05 blue red)
  (colour-below bottle05 red empty)

 )

 (:goal (and
  (closed bottle01)
  (closed bottle02)
  (closed bottle03)
  (closed bottle04)
  (closed bottle05)
 ))

)
