;; Generated by generate_rainbowttles_NO_constants.py
;; seed=201486 profile=optimal-prefix capacity=4 colours=4 bottles=6 scramble_steps=8
;; Constant-free fixed instance: empty is an ordinary problem object.
(define (problem rainbowttles-20-constant-free)
 (:domain rainbowttles-constant-free)
 (:objects
    bottle01 bottle02 bottle03 bottle04 bottle05 bottle06 - bottle
    red green blue yellow empty - colour
 )
 (:init
  (real-colour red)
  (real-colour green)
  (real-colour blue)
  (real-colour yellow)
  (empty-colour empty)

  (= (bottle-capacity bottle01) 4)
  (= (bottle-capacity bottle02) 4)
  (= (bottle-capacity bottle03) 4)
  (= (bottle-capacity bottle04) 4)
  (= (bottle-capacity bottle05) 4)
  (= (bottle-capacity bottle06) 4)

  (= (colour-segments bottle01 red) 4)
  (= (colour-segments bottle01 green) 0)
  (= (colour-segments bottle01 blue) 0)
  (= (colour-segments bottle01 yellow) 0)
  (= (colour-segments bottle01 empty) 0)
  (= (segments-filled bottle01) 4)
  (upper-colour bottle01 red)
  (colour-below bottle01 red empty)

  (= (colour-segments bottle02 red) 0)
  (= (colour-segments bottle02 green) 0)
  (= (colour-segments bottle02 blue) 0)
  (= (colour-segments bottle02 yellow) 0)
  (= (colour-segments bottle02 empty) 0)
  (= (segments-filled bottle02) 0)
  (upper-colour bottle02 empty)

  (= (colour-segments bottle03 red) 0)
  (= (colour-segments bottle03 green) 1)
  (= (colour-segments bottle03 blue) 1)
  (= (colour-segments bottle03 yellow) 2)
  (= (colour-segments bottle03 empty) 0)
  (= (segments-filled bottle03) 4)
  (upper-colour bottle03 green)
  (colour-below bottle03 green yellow)
  (colour-below bottle03 yellow blue)
  (colour-below bottle03 blue empty)

  (= (colour-segments bottle04 red) 0)
  (= (colour-segments bottle04 green) 0)
  (= (colour-segments bottle04 blue) 1)
  (= (colour-segments bottle04 yellow) 2)
  (= (colour-segments bottle04 empty) 0)
  (= (segments-filled bottle04) 3)
  (upper-colour bottle04 blue)
  (colour-below bottle04 blue yellow)
  (colour-below bottle04 yellow empty)

  (= (colour-segments bottle05 red) 0)
  (= (colour-segments bottle05 green) 2)
  (= (colour-segments bottle05 blue) 1)
  (= (colour-segments bottle05 yellow) 0)
  (= (colour-segments bottle05 empty) 0)
  (= (segments-filled bottle05) 3)
  (upper-colour bottle05 blue)
  (colour-below bottle05 blue green)
  (colour-below bottle05 green empty)

  (= (colour-segments bottle06 red) 0)
  (= (colour-segments bottle06 green) 1)
  (= (colour-segments bottle06 blue) 1)
  (= (colour-segments bottle06 yellow) 0)
  (= (colour-segments bottle06 empty) 0)
  (= (segments-filled bottle06) 2)
  (upper-colour bottle06 blue)
  (colour-below bottle06 blue green)
  (colour-below bottle06 green empty)

 )

 (:goal (and
  (closed bottle01)
  (closed bottle02)
  (closed bottle03)
  (closed bottle04)
  (closed bottle05)
  (closed bottle06)
 ))

)
