(define (problem arm_ipar_npuzzle_problem-problem)
 (:domain arm_ipar_npuzzle_problem-domain)
 (:init
              (= (puzzle_0_0) 7)
              (= (puzzle_0_1) 15)
              (= (puzzle_0_2) 4)
              (= (puzzle_0_3) 0)
              (= (puzzle_1_0) 10)
              (= (puzzle_1_1) 9)
              (= (puzzle_1_2) 2)
              (= (puzzle_1_3) 5)
              (= (puzzle_2_0) 12)
              (= (puzzle_2_1) 11)
              (= (puzzle_2_2) 13)
              (= (puzzle_2_3) 6)
              (= (puzzle_3_0) 1)
              (= (puzzle_3_1) 3)
              (= (puzzle_3_2) 14)
              (= (puzzle_3_3) 8)
              (= (total-cost) 0)
 )
 (:goal (and 
           (= (puzzle_0_0) 0)
           (= (puzzle_0_1) 1)
           (= (puzzle_0_2) 2)
           (= (puzzle_0_3) 3)
           (= (puzzle_1_0) 4)
           (= (puzzle_1_1) 5)
           (= (puzzle_1_2) 6)
           (= (puzzle_1_3) 7)
           (= (puzzle_2_0) 8)
           (= (puzzle_2_1) 9)
           (= (puzzle_2_2) 10)
           (= (puzzle_2_3) 11)
           (= (puzzle_3_0) 12)
           (= (puzzle_3_1) 13)
           (= (puzzle_3_2) 14)
           (= (puzzle_3_3) 15)
        )
 )
 (:metric minimize (total-cost))
)
