(define (problem utfr_crim_arm_ipar_plotting_problem-problem)
 (:domain utfr_crim_arm_ipar_plotting_problem-domain)
 (:objects
 )
 (:init
              (= (count_0) 1)
              (= (count_1) 1)
              (= (count_2) 1)
              (= (count_3) 1)
              (= (count_4) 1)
              (= (count_5) 1)
              (= (count_6) 1)
              (= (count_7) 1)
              (= (count_8) 1)
              (= (count_9) 1)
              (= (count_10) 1)
              (= (count_11) 1)
              (= (count_12) 1)
              (= (count_13) 1)
              (= (count_14) 1)
              (= (count_15) 1)
              (= (count_16) 1)
              (= (count_17) 1)
              (= (count_18) 1)
              (= (count_19) 1)
              (= (count_20) 1)
              (= (count_21) 1)
              (= (count_22) 1)
              (= (count_23) 1)
              (= (count_24) 1)
              (= (count_25) 1)
              (= (count_26) 1)
              (= (count_27) 1)
              (= (count_28) 1)
              (= (count_29) 1)
              (= (count_30) 1)
              (= (count_31) 1)
              (= (count_32) 1)
              (= (count_33) 1)
              (= (count_34) 1)
              (= (count_35) 1)
              (= (count_36) 1)
              (= (count_37) 1)
              (= (count_38) 1)
              (= (count_39) 1)
              (= (count_40) 1)
              (= (count_41) 1)
              (= (count_42) 1)
              (= (count_43) 1)
              (= (count_44) 1)
              (= (count_45) 1)
              (= (count_46) 1)
              (= (count_47) 1)
              (= (count_48) 1)
              (blocks_0_0 r)
              (blocks_0_1 r)
              (blocks_0_2 g)
              (blocks_0_3 g)
              (blocks_0_4 b)
              (blocks_0_5 r)
              (blocks_0_6 r)
              (blocks_1_0 y)
              (blocks_1_1 o)
              (blocks_1_2 v)
              (blocks_1_3 o)
              (blocks_1_4 y)
              (blocks_1_5 y)
              (blocks_1_6 r)
              (blocks_2_0 b)
              (blocks_2_1 v)
              (blocks_2_2 b)
              (blocks_2_3 r)
              (blocks_2_4 r)
              (blocks_2_5 o)
              (blocks_2_6 r)
              (blocks_3_0 b)
              (blocks_3_1 b)
              (blocks_3_2 g)
              (blocks_3_3 b)
              (blocks_3_4 r)
              (blocks_3_5 g)
              (blocks_3_6 o)
              (blocks_4_0 y)
              (blocks_4_1 y)
              (blocks_4_2 o)
              (blocks_4_3 v)
              (blocks_4_4 v)
              (blocks_4_5 g)
              (blocks_4_6 g)
              (blocks_5_0 o)
              (blocks_5_1 r)
              (blocks_5_2 o)
              (blocks_5_3 b)
              (blocks_5_4 r)
              (blocks_5_5 v)
              (blocks_5_6 g)
              (blocks_6_0 r)
              (blocks_6_1 b)
              (blocks_6_2 y)
              (blocks_6_3 o)
              (blocks_6_4 o)
              (blocks_6_5 b)
              (blocks_6_6 r)
              (hand w)
              (= (total-cost) 0)
 )
 (:goal (and 
           (<= (+ (count_48) (+ (count_47) (+ (count_46) (+ (count_45) (+ (count_44) (+ (count_43) (+ (count_42) (+ (count_41) (+ (count_40) (+ (count_39) (+ (count_38) (+ (count_37) (+ (count_36) (+ (count_35) (+ (count_34) (+ (count_33) (+ (count_32) (+ (count_31) (+ (count_30) (+ (count_29) (+ (count_28) (+ (count_27) (+ (count_26) (+ (count_25) (+ (count_24) (+ (count_23) (+ (count_22) (+ (count_21) (+ (count_20) (+ (count_19) (+ (count_18) (+ (count_17) (+ (count_16) (+ (count_15) (+ (count_14) (+ (count_13) (+ (count_12) (+ (count_11) (+ (count_10) (+ (count_9) (+ (count_8) (+ (count_7) (+ (count_6) (+ (count_5) (+ (count_4) (+ (count_3) (+ (count_2) (+ (count_1) (count_0))))))))))))))))))))))))))))))))))))))))))))))))) 6)
        )
 )
 (:metric minimize (total-cost))
)
