(define (problem arm_ipar_pancake_problem-problem)
 (:domain arm_ipar_pancake_problem-domain)
 (:init
              (= (pancake_0) 8)
              (= (pancake_1) 6)
              (= (pancake_2) 4)
              (= (pancake_3) 2)
              (= (pancake_4) 3)
              (= (pancake_5) 5)
              (= (pancake_6) 1)
              (= (pancake_7) 0)
              (= (pancake_8) 9)
              (= (pancake_9) 7)
              (= (total-cost) 0)
 )
 (:goal (and 
           (= (pancake_0) 0)
           (= (pancake_1) 1)
           (= (pancake_2) 2)
           (= (pancake_3) 3)
           (= (pancake_4) 4)
           (= (pancake_5) 5)
           (= (pancake_6) 6)
           (= (pancake_7) 7)
           (= (pancake_8) 8)
           (= (pancake_9) 9)
        )
 )
 (:metric minimize (total-cost))
)
