(define (problem utfr_crim_arm_ipar_plotting_problem-problem)
 (:domain utfr_crim_arm_ipar_plotting_problem-domain)
 (:objects
 )
 (:init
              (= (count_0) 1)
              (= (count_1) 1)
              (= (count_2) 1)
              (= (count_3) 1)
              (= (count_4) 1)
              (= (count_5) 1)
              (= (count_6) 1)
              (= (count_7) 1)
              (= (count_8) 1)
              (= (count_9) 1)
              (= (count_10) 1)
              (= (count_11) 1)
              (= (count_12) 1)
              (= (count_13) 1)
              (= (count_14) 1)
              (= (count_15) 1)
              (= (count_16) 1)
              (= (count_17) 1)
              (= (count_18) 1)
              (= (count_19) 1)
              (blocks_0_0 r)
              (blocks_0_1 r)
              (blocks_0_2 g)
              (blocks_0_3 r)
              (blocks_1_0 b)
              (blocks_1_1 g)
              (blocks_1_2 y)
              (blocks_1_3 y)
              (blocks_2_0 b)
              (blocks_2_1 b)
              (blocks_2_2 b)
              (blocks_2_3 g)
              (blocks_3_0 g)
              (blocks_3_1 g)
              (blocks_3_2 g)
              (blocks_3_3 y)
              (blocks_4_0 g)
              (blocks_4_1 b)
              (blocks_4_2 r)
              (blocks_4_3 b)
              (hand w)
              (= (total-cost) 0)
 )
 (:goal (and 
           (<= (+ (count_19) (+ (count_18) (+ (count_17) (+ (count_16) (+ (count_15) (+ (count_14) (+ (count_13) (+ (count_12) (+ (count_11) (+ (count_10) (+ (count_9) (+ (count_8) (+ (count_7) (+ (count_6) (+ (count_5) (+ (count_4) (+ (count_3) (+ (count_2) (+ (count_1) (count_0)))))))))))))))))))) 4)
        )
 )
 (:metric minimize (total-cost))
)
