(define (problem utfr_crim_arm_ipar_plotting_problem-problem)
 (:domain utfr_crim_arm_ipar_plotting_problem-domain)
 (:objects
 )
 (:init
              (= (count_0) 1)
              (= (count_1) 1)
              (= (count_2) 1)
              (= (count_3) 1)
              (= (count_4) 1)
              (= (count_5) 1)
              (= (count_6) 1)
              (= (count_7) 1)
              (= (count_8) 1)
              (= (count_9) 1)
              (= (count_10) 1)
              (= (count_11) 1)
              (blocks_0_0 r)
              (blocks_0_1 r)
              (blocks_0_2 r)
              (blocks_0_3 g)
              (blocks_1_0 r)
              (blocks_1_1 g)
              (blocks_1_2 r)
              (blocks_1_3 r)
              (blocks_2_0 r)
              (blocks_2_1 g)
              (blocks_2_2 r)
              (blocks_2_3 g)
              (hand w)
              (= (total-cost) 0)
 )
 (:goal (and 
           (<= (+ (count_11) (+ (count_10) (+ (count_9) (+ (count_8) (+ (count_7) (+ (count_6) (+ (count_5) (+ (count_4) (+ (count_3) (+ (count_2) (+ (count_1) (count_0)))))))))))) 2)
        )
 )
 (:metric minimize (total-cost))
)
