(define (problem utfr_crim_arm_ipar_plotting_problem-problem)
 (:domain utfr_crim_arm_ipar_plotting_problem-domain)
 (:objects
 )
 (:init
              (= (count_0) 1)
              (= (count_1) 1)
              (= (count_2) 1)
              (= (count_3) 1)
              (= (count_4) 1)
              (= (count_5) 1)
              (= (count_6) 1)
              (= (count_7) 1)
              (= (count_8) 1)
              (= (count_9) 1)
              (= (count_10) 1)
              (= (count_11) 1)
              (= (count_12) 1)
              (= (count_13) 1)
              (= (count_14) 1)
              (= (count_15) 1)
              (= (count_16) 1)
              (= (count_17) 1)
              (= (count_18) 1)
              (= (count_19) 1)
              (= (count_20) 1)
              (= (count_21) 1)
              (= (count_22) 1)
              (= (count_23) 1)
              (= (count_24) 1)
              (= (count_25) 1)
              (= (count_26) 1)
              (= (count_27) 1)
              (= (count_28) 1)
              (= (count_29) 1)
              (blocks_0_0 r)
              (blocks_0_1 r)
              (blocks_0_2 r)
              (blocks_0_3 g)
              (blocks_0_4 r)
              (blocks_0_5 r)
              (blocks_1_0 b)
              (blocks_1_1 r)
              (blocks_1_2 r)
              (blocks_1_3 b)
              (blocks_1_4 r)
              (blocks_1_5 b)
              (blocks_2_0 r)
              (blocks_2_1 g)
              (blocks_2_2 b)
              (blocks_2_3 b)
              (blocks_2_4 g)
              (blocks_2_5 g)
              (blocks_3_0 r)
              (blocks_3_1 r)
              (blocks_3_2 g)
              (blocks_3_3 b)
              (blocks_3_4 g)
              (blocks_3_5 b)
              (blocks_4_0 g)
              (blocks_4_1 b)
              (blocks_4_2 r)
              (blocks_4_3 g)
              (blocks_4_4 b)
              (blocks_4_5 b)
              (hand w)
              (= (total-cost) 0)
 )
 (:goal (and 
           (<= (+ (count_29) (+ (count_28) (+ (count_27) (+ (count_26) (+ (count_25) (+ (count_24) (+ (count_23) (+ (count_22) (+ (count_21) (+ (count_20) (+ (count_19) (+ (count_18) (+ (count_17) (+ (count_16) (+ (count_15) (+ (count_14) (+ (count_13) (+ (count_12) (+ (count_11) (+ (count_10) (+ (count_9) (+ (count_8) (+ (count_7) (+ (count_6) (+ (count_5) (+ (count_4) (+ (count_3) (+ (count_2) (+ (count_1) (count_0)))))))))))))))))))))))))))))) 3)
        )
 )
 (:metric minimize (total-cost))
)
