(define (problem P05_sat)
(:domain PolyCraft)
(:objects
    cell0 cell1 cell2 cell3 cell4 cell5 cell6 cell7 cell8 cell9 cell10 cell11 cell12 cell13 cell14 cell15 cell16 cell17 cell18 cell19 cell20 cell21 cell22 cell23 cell24 - cell
)
(:init
		(position cell7)
		(crafting_table_cell cell18)
		(= (toxicity) 0)
		(air_cell cell0)
		(tree_cell cell1)
		(air_cell cell2)
		(tree_cell cell3)
		(tree_cell cell4)
		(air_cell cell5)
		(tree_cell cell6)
		(tree_cell cell7)
		(tree_cell cell8)
		(air_cell cell9)
		(tree_cell cell10)
		(air_cell cell11)
		(tree_cell cell12)
		(air_cell cell13)
		(tree_cell cell14)
		(tree_cell cell15)
		(tree_cell cell16)
		(air_cell cell17)
		(tree_cell cell18)
		(tree_cell cell19)
		(tree_cell cell20)
		(tree_cell cell21)
		(tree_cell cell22)
		(tree_cell cell23)
		(tree_cell cell24)
		(= (count_log_in_inventory) 0)
		(= (count_planks_in_inventory) 0)
		(= (count_stick_in_inventory) 0)
		(= (count_tree_tap_in_inventory) 0)
		(= (count_sack_polyisoprene_pellets_in_inventory) 0)
		(= (count_pogo_stick) 0)
)
(:goal
  (and
    (>= (count_pogo_stick) 5)
  )
)
)
