(define (problem foresfire03)
(:domain forestfire)
(:objects bot1 - bot
          axe1 - axe
          grass1_1 grass2_1 grass3_1 grass2_2 grass1_3 grass2_3 grass3_3 - grass
          bushes1_2 bushes3_2 - bushes
)
(:init (connected bushes1_2 grass1_3)
       (connected bushes3_2 grass2_2)
       (connected grass2_3 grass3_3)
       (connected grass2_2 bushes3_2)
       (connected grass2_3 grass2_2)
       (connected grass1_1 grass2_1)
       (connected grass1_3 bushes1_2)
       (connected grass2_2 bushes1_2)
       (connected grass3_3 bushes3_2)
       (connected grass2_2 grass2_1)
       (connected grass2_1 grass2_2)
       (connected bushes1_2 grass1_1)
       (connected bushes3_2 grass3_1)
       (connected bushes1_2 grass2_2)
       (connected grass2_3 grass1_3)
       (connected bushes3_2 grass3_3)
       (connected grass3_1 grass2_1)
       (connected grass2_1 grass1_1)
       (connected grass2_1 grass3_1)
       (connected grass3_1 bushes3_2)
       (connected grass2_2 grass2_3)
       (connected grass1_1 bushes1_2)
       (connected grass1_3 grass2_3)
       (connected grass3_3 grass2_3)
       
       (= (tree grass1_1) 0)
       (= (tree grass2_1) 0)
       (= (tree grass3_1) 0)
       (= (tree bushes1_2) 0)
       (= (tree grass2_2) 3)
       (= (tree bushes3_2) 0)
       (= (tree grass1_3) 0)
       (= (tree grass2_3) 0)
       (= (tree grass3_3) 0)
       
       (= (fire grass1_1) 0)
       (= (fire grass2_1) 0)
       (= (fire grass3_1) 0)
       (= (fire bushes1_2) 0)
       (= (fire grass2_2) 0)
       (= (fire bushes3_2) 0)
       (= (fire grass1_3) 3)
       (= (fire grass2_3) 3)
       (= (fire grass3_3) 3)
       
       (= (max-water bushes1_2) 1)
       (= (max-water bushes3_2) 1)
       
       (at bot1 grass1_1)
       (= (water-capacity bot1) 3)
       (= (has-water bot1) 0)
       
       (pond grass1_1)
       (pond grass3_1)
       (at axe1 grass1_1)
       (= (durability axe1) 3)
       
       (= (cost) 0))
(:goal (and (= (fire grass1_3) 0)
            (= (fire grass2_3) 0)
            (= (fire grass3_3) 0)))
(:metric minimize (cost))
)