#!/usr/bin/env python3
"""Instance generator for the Factory Robot domain.

Scaling dimensions:
  - Number of robots (R): increases ground actions quadratically (robot x station)
  - Number of stations (S): increases movement actions and connectivity
  - Workload target (W): increases plan length (more work/recharge/cool cycles)
  - Temperature limit (T): tighter limits force more cooling detours

Usage:
  python generate.py                          # default: 2 robots, 3 stations
  python generate.py --robots 4 --stations 5  # larger instance
  python generate.py --robots 3 --workload 20 --max-temp 10  # harder goals
  python generate.py --seed 42                # reproducible randomization

The generated problem is written to stdout.
"""

import argparse
import random
import sys
from typing import Optional


def generate(robots: int, stations: int, workload: int, max_temp_limit: int,
             seed: Optional[int], command: Optional[str] = None) -> str:
    rng = random.Random(seed)

    # Name objects.
    robot_names = [f"r{i}" for i in range(robots)]
    station_names = []
    # Always include one charging and one cooling station; rest are assembly.
    station_names.append("charging")
    station_names.append("cooling")
    for i in range(stations - 2):
        station_names.append(f"assembly{i}" if stations > 3 else "assembly")

    # Robot characteristics (constant fluents).
    robot_capacity = {r: rng.choice([80, 100, 120, 150]) for r in robot_names}
    robot_work_cost = {r: rng.choice([8, 10, 12, 15]) for r in robot_names}
    robot_max_temp = {r: max_temp_limit + rng.randint(0, 5) for r in robot_names}
    robot_efficiency = {r: rng.choice([2, 3, 4]) for r in robot_names}

    # Station characteristics.
    cooling_power = {}
    for s in station_names:
        if s == "cooling":
            cooling_power[s] = rng.choice([4, 5, 6])
        else:
            cooling_power[s] = 0

    # Initial positions: distribute robots across distinct stations.
    # With mutual exclusion, no two robots can share a station.
    assert robots <= stations, \
        f"Need at least as many stations ({stations}) as robots ({robots})"
    positions = list(station_names)
    rng.shuffle(positions)
    initial_positions = {}
    for i, r in enumerate(robot_names):
        initial_positions[r] = positions[i]

    # Free stations: those not occupied initially.
    occupied = set(initial_positions.values())
    free_stations = [s for s in station_names if s not in occupied]

    # Initial energy: start at full or near-full capacity.
    initial_energy = {r: robot_capacity[r] - rng.randint(0, 20) for r in robot_names}

    # Build connectivity: fully connected network.
    connections = []
    for i, s1 in enumerate(station_names):
        for j, s2 in enumerate(station_names):
            if i != j:
                connections.append((s1, s2))

    # Per-robot workload targets: scale around the given workload param.
    workload_targets = {}
    for r in robot_names:
        workload_targets[r] = workload + rng.randint(-2, 2)
        workload_targets[r] = max(1, workload_targets[r])

    # Temperature goal: only first robot has a temperature constraint.
    temp_target = max_temp_limit

    # Build PDDL.
    lines = []
    if command:
        lines.append(f";; Generated by: {command}")
    lines.append(f";; Factory Robot — {robots} robots, {stations} stations (seed={seed})")
    lines.append("")
    lines.append(f"(define (problem factory-{robots}r-{stations}s)")
    lines.append("  (:domain factory-robot)")
    lines.append("")

    # Objects.
    lines.append("  (:objects")
    lines.append(f"    {' '.join(robot_names)} - robot")
    lines.append(f"    {' '.join(station_names)} - station")
    lines.append("  )")
    lines.append("")

    # Init.
    lines.append("  (:init")

    # Positions.
    for r in robot_names:
        lines.append(f"    (at {r} {initial_positions[r]})")

    # Connectivity.
    for s1, s2 in connections:
        lines.append(f"    (connected {s1} {s2})")

    # Station equipment.
    lines.append("    (has-charger charging)")
    lines.append("    (has-calibrator cooling)")

    # Station occupancy.
    for s in free_stations:
        lines.append(f"    (free {s})")

    # Robots start calibrated.
    for r in robot_names:
        lines.append(f"    (calibrated {r})")

    lines.append("")

    # Robot state.
    for r in robot_names:
        lines.append(f"    (= (energy {r}) {initial_energy[r]})")
    for r in robot_names:
        lines.append(f"    (= (workload {r}) 0)")
    for r in robot_names:
        lines.append(f"    (= (temperature {r}) 0)")
    for r in robot_names:
        lines.append(f"    (= (production {r}) 0)")

    lines.append("")

    # Constants.
    for r in robot_names:
        lines.append(f"    (= (capacity {r}) {robot_capacity[r]})")
    for r in robot_names:
        lines.append(f"    (= (work-cost {r}) {robot_work_cost[r]})")
    for r in robot_names:
        lines.append(f"    (= (max-temp {r}) {robot_max_temp[r]})")
    for r in robot_names:
        lines.append(f"    (= (efficiency {r}) {robot_efficiency[r]})")
    for s in station_names:
        lines.append(f"    (= (cooling-power {s}) {cooling_power[s]})")

    lines.append("  )")
    lines.append("")

    # Goal.
    lines.append("  (:goal (and")
    for r in robot_names:
        lines.append(f"    (>= (workload {r}) {workload_targets[r]})")
    lines.append(f"    (<= (temperature {robot_names[0]}) {temp_target})")
    lines.append("  ))")

    lines.append(")")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate Factory Robot problem instances.")
    parser.add_argument("--robots", "-r", type=int, default=2,
                        help="Number of robots (default: 2)")
    parser.add_argument("--stations", "-s", type=int, default=3,
                        help="Number of stations (default: 3, min: 2)")
    parser.add_argument("--workload", "-w", type=int, default=5,
                        help="Base workload target per robot (default: 5)")
    parser.add_argument("--max-temp", "-t", type=int, default=15,
                        help="Temperature safety limit (default: 15)")
    parser.add_argument("--seed", type=int, default=None,
                        help="Random seed for reproducibility")
    parser.add_argument("-o", "--output", type=str, default=None,
                        help="Output file (default: stdout)")
    args = parser.parse_args()

    if args.stations < 2:
        parser.error("Need at least 2 stations (charging + cooling)")
    if args.robots > args.stations:
        parser.error(f"Need at least as many stations as robots "
                     f"(got {args.robots} robots, {args.stations} stations)")

    # Reconstruct the command line for the PDDL header comment.
    cmd_parts = ["python generate.py"]
    if args.robots != 2:
        cmd_parts.append(f"--robots {args.robots}")
    if args.stations != 3:
        cmd_parts.append(f"--stations {args.stations}")
    if args.workload != 5:
        cmd_parts.append(f"--workload {args.workload}")
    if args.max_temp != 15:
        cmd_parts.append(f"--max-temp {args.max_temp}")
    if args.seed is not None:
        cmd_parts.append(f"--seed {args.seed}")
    command = " ".join(cmd_parts)

    result = generate(args.robots, args.stations, args.workload,
                      args.max_temp, args.seed, command=command)

    if args.output:
        with open(args.output, "w") as f:
            f.write(result)
        print(f"Written to {args.output}", file=sys.stderr)
    else:
        print(result)


if __name__ == "__main__":
    main()
