(define (problem arm_ipar_pancake_problem-problem)
 (:domain arm_ipar_pancake_problem-domain)
 (:init
              (= (pancake_0) 3)
              (= (pancake_1) 17)
              (= (pancake_2) 13)
              (= (pancake_3) 9)
              (= (pancake_4) 19)
              (= (pancake_5) 15)
              (= (pancake_6) 12)
              (= (pancake_7) 6)
              (= (pancake_8) 14)
              (= (pancake_9) 10)
              (= (pancake_10) 5)
              (= (pancake_11) 0)
              (= (pancake_12) 16)
              (= (pancake_13) 2)
              (= (pancake_14) 18)
              (= (pancake_15) 1)
              (= (pancake_16) 7)
              (= (pancake_17) 8)
              (= (pancake_18) 4)
              (= (pancake_19) 11)
              (= (total-cost) 0)
 )
 (:goal (and 
           (= (pancake_0) 0)
           (= (pancake_1) 1)
           (= (pancake_2) 2)
           (= (pancake_3) 3)
           (= (pancake_4) 4)
           (= (pancake_5) 5)
           (= (pancake_6) 6)
           (= (pancake_7) 7)
           (= (pancake_8) 8)
           (= (pancake_9) 9)
           (= (pancake_10) 10)
           (= (pancake_11) 11)
           (= (pancake_12) 12)
           (= (pancake_13) 13)
           (= (pancake_14) 14)
           (= (pancake_15) 15)
           (= (pancake_16) 16)
           (= (pancake_17) 17)
           (= (pancake_18) 18)
           (= (pancake_19) 19)
        )
 )
 (:metric minimize (total-cost))
)
