(define (problem mprime-x-6)
   (:domain mystery-prime-typed)
   (:objects tomato rice popover cantelope tuna papaya chicken
             scallop beef pistachio muffin mutton potato wonderbread
             snickers marzipan turkey onion bacon - food
             love intoxication rest aesthetics achievement excitement
             satisfaction curiosity lubricity understanding triumph
             - pleasure
             anger hangover sciatica grief abrasion prostatitis angina
             boils loneliness - pain
)
   (:init
(= (harmony excitement) 3)
(= (locale onion) 4)
          (eats muffin bacon)
          (eats scallop chicken)
(= (harmony satisfaction) 2)
          (eats tuna rice)
          (eats mutton turkey)
(= (locale rice) 0)
          (eats chicken papaya)
(= (harmony rest) 3)
          (eats chicken turkey)
(= (harmony achievement) 1)
          (eats wonderbread marzipan)
          (craves aesthetics cantelope)
(= (harmony aesthetics) 3)
          (eats snickers potato)
(= (locale pistachio) 3)
(= (locale potato) 3)
          (eats turkey chicken)
          (eats onion turkey)
          (eats scallop beef)
(= (locale cantelope) 4)
          (eats tomato cantelope)
          (eats marzipan wonderbread)
          (craves angina snickers)
          (eats turkey onion)
          (eats turkey snickers)
          (eats beef papaya)
(= (harmony curiosity) 3)
(= (locale beef) 2)
          (craves rest popover)
(= (locale bacon) 6)
          (eats cantelope tomato)
(= (locale tomato) 3)
          (craves boils onion)
          (eats rice tuna)
          (craves excitement scallop)
          (craves understanding marzipan)
          (eats popover rice)
          (craves triumph turkey)
          (eats papaya beef)
(= (locale mutton) 2)
          (craves anger popover)
          (eats bacon wonderbread)

          (eats beef tuna)
          (eats onion mutton)
(= (locale wonderbread) 5)
          (craves satisfaction pistachio)
(= (harmony triumph) 3)
(= (locale muffin) 3)
          (craves abrasion beef)

(= (harmony intoxication) 2)


          (craves intoxication rice)
          (eats mutton onion)
(= (locale turkey) 3)
          (eats tuna beef)
          (eats turkey mutton)
          (eats bacon mutton)
(= (locale popover) 1)
          (craves hangover cantelope)
(= (locale marzipan) 0)
(= (locale scallop) 1)
          (eats tomato tuna)
(= (locale chicken) 2)
(= (locale snickers) 4)
          (eats muffin pistachio)
(= (locale tuna) 3)
          (eats wonderbread bacon)
          (eats potato marzipan)
          (eats marzipan potato)

          (eats onion pistachio)
          (eats pistachio muffin)
          (eats cantelope popover)
          (eats wonderbread turkey)
          (craves prostatitis muffin)
          (craves love tomato)
          (eats bacon muffin)
          (eats chicken scallop)
          (eats mutton bacon)
          (craves lubricity wonderbread)
(= (harmony love) 1)

          (eats popover cantelope)

          (craves sciatica papaya)
(= (harmony lubricity) 3)
          (eats pistachio onion)
          (eats turkey wonderbread)
          (eats potato snickers)
(= (locale papaya) 1)
          (eats beef scallop)
(= (harmony understanding) 1)
          (craves loneliness bacon)

          (craves achievement chicken)
          (eats papaya chicken)
          (eats rice popover)
          (eats snickers turkey)
          (craves grief chicken)

          (craves curiosity potato)
          (eats tuna tomato))
   (:goal (and (craves anger turkey)
               (craves abrasion turkey))))
