(define (problem mprime-x-8)
   (:domain mystery-prime-typed)
   (:objects rice okra hotdog tofu muffin tuna pork cantelope turkey
             baguette arugula wonderbread pepper flounder lobster scallop
             tomato pistachio - food
             achievement love triumph stimulation learning lubricity rest
             aesthetics excitement - pleasure
             sciatica hangover anxiety abrasion anger - pain
)
   (:init
(= (harmony learning) 2)

          (eats turkey baguette)
          (eats muffin tuna)
          (eats flounder wonderbread)
(= (harmony stimulation) 1)
          (eats wonderbread scallop)
          (craves excitement tomato)
          (eats tuna muffin)
          (eats pistachio arugula)
(= (harmony achievement) 2)
(= (harmony rest) 3)
(= (locale pork) 3)
          (craves hangover muffin)
          (eats rice tofu)
(= (locale flounder) 1)
          (eats cantelope arugula)

          (eats pork lobster)
          (craves lubricity arugula)

          (eats okra hotdog)
(= (locale tuna) 4)
          (craves sciatica okra)
          (craves anxiety muffin)
          (eats flounder lobster)
(= (locale scallop) 2)
          (eats tuna rice)
(= (locale turkey) 1)
          (craves love okra)
          (eats okra wonderbread)
(= (locale tofu) 1)
          (eats arugula pistachio)
          (eats rice tuna)

          (craves abrasion baguette)
          (eats baguette turkey)
          (eats tomato scallop)
          (eats tuna okra)

(= (locale tomato) 3)
          (eats scallop tomato)
(= (locale pepper) 1)
          (eats hotdog okra)
          (craves triumph hotdog)
          (eats hotdog tofu)
(= (locale cantelope) 2)
          (eats muffin rice)
          (craves learning cantelope)
          (craves anger baguette)
          (eats muffin tofu)
          (craves rest wonderbread)
(= (locale hotdog) 0)
          (eats wonderbread flounder)
          (eats wonderbread okra)
          (eats tofu rice)
(= (harmony love) 3)
          (craves achievement rice)
          (eats baguette tomato)
(= (harmony aesthetics) 2)
(= (locale rice) 0)
          (eats tomato baguette)
          (eats tofu muffin)
          (eats tofu hotdog)
(= (locale wonderbread) 1)
          (eats arugula cantelope)
(= (locale pistachio) 2)
          (eats rice muffin)
          (eats scallop wonderbread)
          (eats pistachio pepper)
          (eats lobster pork)
          (eats lobster flounder)
          (eats pepper turkey)
(= (locale lobster) 1)


          (eats pork cantelope)
(= (locale baguette) 3)
(= (harmony excitement) 3)
(= (locale okra) 3)
(= (harmony triumph) 2)
          (eats okra tuna)
          (eats cantelope pork)
          (eats turkey pepper)
(= (harmony lubricity) 1)
(= (locale muffin) 0)
          (craves aesthetics scallop)
          (craves stimulation muffin)
          (eats pepper pistachio)
(= (locale arugula) 0))
   (:goal (and (craves anxiety wonderbread))))
