(define (problem mprime-x-10)
   (:domain mystery-prime-typed)
   (:objects tofu snickers popover lamb potato melon beef pork bacon
             orange ham kale pepper hamburger cantelope flounder
             grapefruit wurst arugula - food
             triumph stimulation expectation rest love satisfaction
             learning aesthetics intoxication - pleasure
             laceration depression loneliness hangover prostatitis angina
             anger grief anxiety sciatica jealousy boils dread
             loneliness-1 grief-2 abrasion dread-8 angina-3 sciatica-4 anger-7
             abrasion-5 hangover-6 jealousy-16 anxiety-12 prostatitis-13
             depression-14 boils-15 loneliness-9 anger-10 laceration-11
             angina-30 dread-31 boils-32 laceration-27 jealousy-28
             hangover-29 prostatitis-24 anxiety-25 grief-26 - pain
             )
   (:init (eats snickers potato)
          (eats wurst grapefruit)

          (craves prostatitis-13 pepper)
          (eats flounder kale)
          (eats ham pork)
          (= (harmony triumph) 3)
          (eats arugula hamburger)
          (eats beef snickers)
          (craves expectation beef)
          (craves loneliness snickers)
          (craves satisfaction ham)
          (= (locale kale) 2)
          (= (locale ham) 4)

          (eats beef ham)
          (craves laceration-11 hamburger)
          (eats arugula cantelope)
          (craves aesthetics flounder)
          (craves anger popover)
          (craves anxiety-25 arugula)
          (eats beef arugula)
          (craves boils-15 pepper)
          (eats pepper cantelope)
          (eats orange beef)
          (eats hamburger cantelope)
          (= (harmony satisfaction) 2)
          (craves jealousy melon)
          (eats hamburger wurst)
          (eats pork bacon)
          (eats kale flounder)
          (eats tofu lamb)
          (= (locale potato) 2)
          (eats popover melon)
          (craves stimulation melon)
          (= (locale grapefruit) 3)
          (= (harmony expectation) 3)
          (craves dread-31 cantelope)
          (craves anger-7 orange)

          (eats kale arugula)
          (craves dread beef)
          (craves loneliness-9 hamburger)
          (craves hangover-6 ham)
          (craves grief lamb)
          (eats ham beef)
          (craves boils-32 cantelope)
          (eats cantelope hamburger)
          (eats arugula beef)
          (craves love orange)
          (eats pork ham)
          (= (locale tofu) 0)
          (craves depression snickers)
          (craves angina-30 cantelope)
          (craves jealousy-16 kale)
          (craves anxiety potato)
          (craves learning pepper)
          (= (locale orange) 2)
          (= (harmony aesthetics) 2)
          (= (harmony rest) 1)
          (eats wurst hamburger)
          (eats cantelope arugula)
          (craves prostatitis popover)
          (eats lamb tofu)
          (craves intoxication grapefruit)
          (craves abrasion pork)
          (eats grapefruit pepper)
          (= (locale hamburger) 2)
          (= (locale snickers) 4)
          (= (locale pork) 5)
          (eats cantelope flounder)

          (craves boils melon)
          (eats beef orange)
          (eats orange pork)
          (= (harmony love) 1)
          (craves hangover popover)
          (eats cantelope pepper)
          (eats bacon orange)
          (eats orange bacon)
          (craves grief-26 arugula)
          (craves angina-3 bacon)
          (eats potato melon)
          (= (harmony stimulation) 3)
          (craves laceration snickers)
          (craves sciatica melon)

          (craves jealousy-28 grapefruit)
          (= (harmony learning) 1)
          (craves loneliness-1 pork)
          (craves laceration-27 grapefruit)
          (eats flounder cantelope)
          (craves depression-14 pepper)
          (eats popover tofu)
          (craves hangover-29 grapefruit)
          (eats bacon pork)
          (= (locale beef) 1)
          (craves rest pork)
          (eats melon potato)
          (= (locale bacon) 4)
          (eats snickers beef)
          (eats arugula kale)
          (= (locale cantelope) 2)
          (eats hamburger arugula)
          (= (locale flounder) 1)
          (eats tofu popover)
          (craves dread-8 bacon)
          (craves prostatitis-24 arugula)
          (craves abrasion-5 ham)
          (= (locale arugula) 1)
          (eats melon popover)

          (eats lamb snickers)
          (craves angina popover)
          (= (locale wurst) 4)

          (craves triumph tofu)
          (eats potato snickers)

          (= (locale pepper) 3)
          (craves anxiety-12 pepper)
          (eats pork orange)
          (eats snickers lamb)
          (eats grapefruit wurst)
          (= (locale melon) 4)
          (craves grief-2 pork)
          (craves anger-10 hamburger)
          (craves sciatica-4 bacon)
          (= (locale popover) 3)
          (= (locale lamb) 1)
          (= (harmony intoxication) 2)
          (eats pepper grapefruit))
   (:goal (and (craves jealousy-16 tofu))))
