(define (problem mprime-x-7)
   (:domain mystery-prime-typed)
   (:objects mutton haroset popover shrimp snickers pepper pea
             muffin lobster pear - food
             stimulation learning - pleasure
             grief depression anger loneliness angina jealousy hangover
             boils dread sciatica abrasion prostatitis laceration
             anxiety dread-3 depression-4 abrasion-1 loneliness-2
             angina-8 sciatica-16 grief-5 anger-6 prostatitis-7 boils-15
             - pain
)
   (:init
(craves angina-8 muffin)
(= (locale muffin) 0)

          (eats mutton muffin)
          (eats pepper pea)
          (craves boils-15 pear)
          (craves anger mutton)
          (craves abrasion snickers)
          (eats mutton pea)
(= (locale pea) 2)
          (eats muffin popover)
          (eats pea mutton)
(= (harmony stimulation) 1)
          (craves depression-4 pea)
(= (locale popover) 1)
          (craves abrasion-1 pea)
          (eats popover lobster)
(= (locale shrimp) 2)
          (eats snickers shrimp)
          (craves hangover shrimp)
          (craves learning pea)
          (craves angina haroset)
          (eats lobster haroset)
          (eats shrimp snickers)
          (eats shrimp pepper)
          (craves stimulation snickers)
          (eats pepper pear)
          (craves laceration pepper)
          (eats pepper shrimp)
          (craves sciatica-16 lobster)
          (craves sciatica snickers)
          (craves grief-5 lobster)
          (craves anger-6 lobster)
(= (locale snickers) 0)
          (eats shrimp haroset)
          (eats pea pepper)
          (eats pea snickers)
          (craves jealousy popover)
          (eats muffin lobster)
          (craves anxiety pepper)
(= (locale haroset) 0)

          (craves loneliness-2 pea)
(= (locale pepper) 1)
          (eats pear lobster)
          (eats lobster muffin)
          (eats popover muffin)
          (craves grief mutton)
          (eats popover snickers)
(= (locale mutton) 0)
          (eats lobster pear)
          (craves loneliness haroset)
          (eats lobster popover)
          (craves dread-3 pea)
          (eats snickers popover)
          (craves dread snickers)
          (eats snickers pea)
          (eats haroset lobster)
          (craves prostatitis snickers)
          (craves prostatitis-7 lobster)
(= (locale lobster) 3)
(= (harmony learning) 1)
          (eats pear pepper)


          (eats haroset shrimp)
          (craves depression mutton)
(= (locale pear) 0)
          (eats muffin mutton)
          (craves boils shrimp))
   (:goal (and (craves jealousy muffin))))
