(define (problem mprime-x-3)
   (:domain mystery-prime-typed)
   (:objects pepper pea lemon snickers marzipan popover melon orange
             chocolate ham mutton - food
             entertainment triumph love satisfaction - pleasure
             laceration anxiety grief depression boils angina hangover
             jealousy - pain
)
   (:init 
          (eats orange mutton)
(= (harmony satisfaction) 2)
          (craves angina orange)
          (craves grief marzipan)
          (eats pea snickers)
          (eats popover pepper)

          (eats mutton orange)


(= (harmony triumph) 2)
          (eats marzipan pea)
(= (locale popover) 3)
(= (locale ham) 4)
          (eats mutton melon)
          (craves jealousy ham)
          (eats pea pepper)
          (eats pepper melon)
(= (locale melon) 4)
(= (locale pea) 2)
          (craves boils melon)
          (eats popover lemon)
          (craves laceration pepper)
          (eats popover marzipan)
          (eats chocolate ham)
(= (locale mutton) 1)
          (eats melon ham)

(= (harmony love) 2)
          (eats marzipan snickers)
          (eats pepper popover)
(= (locale lemon) 0)
          (craves triumph popover)

          (eats ham melon)
(= (locale marzipan) 2)
          (eats chocolate orange)
          (eats marzipan popover)
          (eats orange chocolate)
          (eats snickers pea)
          (eats pea marzipan)
(= (harmony entertainment) 1)
          (eats lemon pea)
          (eats melon pepper)
(= (locale orange) 2)
          (craves love orange)
          (craves anxiety snickers)
(= (locale pepper) 4)
          (eats melon mutton)
          (eats pepper pea)
(= (locale chocolate) 1)
          (eats ham chocolate)
          (craves entertainment pepper)
          (eats snickers marzipan)

          (craves satisfaction mutton)
          (eats lemon popover)
(= (locale snickers) 2)
          (eats pea lemon)
          (craves depression popover)
          (craves hangover chocolate)
)
   (:goal (and (craves hangover ham))))
