#!/usr/bin/perl -w

for($i = 1; $i <= 30; ++$i){
	open IN, "< part1";
	$number = $i;
	if($i < 10){
		$number = "0" . $i;
	}
	open OUT, "> pfile$number.pddl";
	while(<IN>){
		print OUT $_;
	}

        if($i < 10){
	  $needed = 1000 + 10*$i;
	} else {
	   $needed = 1000 + 50 * ($i-7);
	}
	$cap = ($needed-1000)/20;
	if($cap =~m/\./){
	  $cap += 0.5;
	}

	print OUT "\t(= (stored_capacity) $cap)\n";
	print OUT "\t(= (funds) 1000)\n";
	print OUT ")\n";

	print OUT "\t (:goal (and\n";
	
	print OUT "\t (>= (funds) $needed)\n";

        print OUT "\t)\n)\n)";

}
