(define (problem arm_ipar_pancake_problem-problem)
 (:domain arm_ipar_pancake_problem-domain)
 (:init
              (= (pancake_0) 10)
              (= (pancake_1) 8)
              (= (pancake_2) 15)
              (= (pancake_3) 13)
              (= (pancake_4) 11)
              (= (pancake_5) 4)
              (= (pancake_6) 6)
              (= (pancake_7) 14)
              (= (pancake_8) 5)
              (= (pancake_9) 3)
              (= (pancake_10) 2)
              (= (pancake_11) 17)
              (= (pancake_12) 9)
              (= (pancake_13) 0)
              (= (pancake_14) 19)
              (= (pancake_15) 16)
              (= (pancake_16) 12)
              (= (pancake_17) 18)
              (= (pancake_18) 7)
              (= (pancake_19) 1)
              (= (total-cost) 0)
 )
 (:goal (and 
           (= (pancake_0) 0)
           (= (pancake_1) 1)
           (= (pancake_2) 2)
           (= (pancake_3) 3)
           (= (pancake_4) 4)
           (= (pancake_5) 5)
           (= (pancake_6) 6)
           (= (pancake_7) 7)
           (= (pancake_8) 8)
           (= (pancake_9) 9)
           (= (pancake_10) 10)
           (= (pancake_11) 11)
           (= (pancake_12) 12)
           (= (pancake_13) 13)
           (= (pancake_14) 14)
           (= (pancake_15) 15)
           (= (pancake_16) 16)
           (= (pancake_17) 17)
           (= (pancake_18) 18)
           (= (pancake_19) 19)
        )
 )
 (:metric minimize (total-cost))
)
