(define (problem arm_ipar_pancake_problem-problem)
 (:domain arm_ipar_pancake_problem-domain)
 (:init
              (= (pancake_0) 15)
              (= (pancake_1) 4)
              (= (pancake_2) 0)
              (= (pancake_3) 6)
              (= (pancake_4) 18)
              (= (pancake_5) 2)
              (= (pancake_6) 10)
              (= (pancake_7) 19)
              (= (pancake_8) 16)
              (= (pancake_9) 17)
              (= (pancake_10) 20)
              (= (pancake_11) 3)
              (= (pancake_12) 22)
              (= (pancake_13) 14)
              (= (pancake_14) 5)
              (= (pancake_15) 21)
              (= (pancake_16) 23)
              (= (pancake_17) 9)
              (= (pancake_18) 11)
              (= (pancake_19) 12)
              (= (pancake_20) 1)
              (= (pancake_21) 7)
              (= (pancake_22) 13)
              (= (pancake_23) 8)
              (= (pancake_24) 24)
              (= (total-cost) 0)
 )
 (:goal (and 
           (= (pancake_0) 0)
           (= (pancake_1) 1)
           (= (pancake_2) 2)
           (= (pancake_3) 3)
           (= (pancake_4) 4)
           (= (pancake_5) 5)
           (= (pancake_6) 6)
           (= (pancake_7) 7)
           (= (pancake_8) 8)
           (= (pancake_9) 9)
           (= (pancake_10) 10)
           (= (pancake_11) 11)
           (= (pancake_12) 12)
           (= (pancake_13) 13)
           (= (pancake_14) 14)
           (= (pancake_15) 15)
           (= (pancake_16) 16)
           (= (pancake_17) 17)
           (= (pancake_18) 18)
           (= (pancake_19) 19)
           (= (pancake_20) 20)
           (= (pancake_21) 21)
           (= (pancake_22) 22)
           (= (pancake_23) 23)
           (= (pancake_24) 24)
        )
 )
 (:metric minimize (total-cost))
)
