(define (problem arm_ipar_pancake_problem-problem)
 (:domain arm_ipar_pancake_problem-domain)
 (:init
              (= (pancake_0) 2)
              (= (pancake_1) 0)
              (= (pancake_2) 9)
              (= (pancake_3) 7)
              (= (pancake_4) 5)
              (= (pancake_5) 4)
              (= (pancake_6) 12)
              (= (pancake_7) 3)
              (= (pancake_8) 13)
              (= (pancake_9) 14)
              (= (pancake_10) 6)
              (= (pancake_11) 1)
              (= (pancake_12) 10)
              (= (pancake_13) 11)
              (= (pancake_14) 8)
              (= (total-cost) 0)
 )
 (:goal (and 
           (= (pancake_0) 0)
           (= (pancake_1) 1)
           (= (pancake_2) 2)
           (= (pancake_3) 3)
           (= (pancake_4) 4)
           (= (pancake_5) 5)
           (= (pancake_6) 6)
           (= (pancake_7) 7)
           (= (pancake_8) 8)
           (= (pancake_9) 9)
           (= (pancake_10) 10)
           (= (pancake_11) 11)
           (= (pancake_12) 12)
           (= (pancake_13) 13)
           (= (pancake_14) 14)
        )
 )
 (:metric minimize (total-cost))
)
